In [16]:
import numpy as np
import pandas as pd

In [17]:
#To read data from the csv file
data = pd.read_csv("Data.csv")
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [18]:
#Making array of all attributes
d= np.array(data)[:,:-1]
d

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [19]:
#segragating the target that has positive and negative examples
target = np.array(data)[:,-1]
target

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [20]:
#training function to implement find-s algorithm
def train(c,t):
  for i, val in enumerate(t):
    if val == "Yes":
      specific_hypothesis = c[i].copy()
      break
  
  for i, val in enumerate(c):
    if t[i] == "Yes":
      for x in range(len(specific_hypothesis)):
        if val[x] != specific_hypothesis[x]:
          specific_hypothesis[x] = '?'
        else:
          pass
  return specific_hypothesis

In [21]:
#obtaining the final hypothesis
train(d,target)

array(['?', '?', '?'], dtype=object)